## SpringCloud-Service02-Eureka2 專用的配置檔案
## Eureka
server:
  port: 28081

#設定 Eureka 註冊的路徑   
#register-with-eureka 代表不註冊自己的service 
#register-with-eureka: false
#fetch-registry: false
eureka:
  instance:
        hostname: eureka02
  client:
      register-with-eureka: false
      fetch-registry: false
      serviceUrl:
          defaultZone: http://eureka01:28080/eureka/ 