## SpringCloud-Service02-Eureka 專用的配置檔案
## Eureka
server:
  port: 28080

#設定 Eureka 註冊的路徑   
#register-with-eureka 代表不註冊自己的service 
#register-with-eureka: false
#fetch-registry: false
eureka:
  instance:
    hostname: eureka01
  client:
    register-with-eureka: false
    fetch-registry: false
# 開發環境使用的配置方式
    serviceUrl:
      defaultZone: http://eureka01:${server.port}/eureka/

# 使用外部Tomcat的配置方式
#     defaultZone: http://eureka01:${server.port}/SpringCloud-Service02-Eureka/eureka/
# 取得另一個eureka service
#     defaultZone: http://eureka02:28081/eureka/   