## SpringCloud-Service02-Eureka 專用的配置檔案
## Eureka
server:
  port: 28080

#設定 Eureka 註冊的路徑   
#register-with-eureka 代表不註冊自己的service 
#register-with-eureka: false
#fetch-registry: false
eureka:
  instance:
    hostname: eureka01
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka01:${server.port}/eureka/
#    serviceUrl:
#      defaultZone: http://eureka02:28081/eureka/   