#設定 Eureka 註冊的路徑   
#register-with-eureka 代表不註冊自己的service 
#register-with-eureka: false
#fetch-registry: false
eureka:
  instance:
    hostname: eureka01
  client:
    register-with-eureka: false
    fetch-registry: false
#    serviceUrl:
#      defaultZone: http://eureka01:28990/eureka/
    serviceUrl:
      defaultZone: http://eureka02:28991/eureka/   