## SpringCloud-Service11-Business 專用的配置檔案
server:
  port: 38080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testschema?useSSL=false&serverTimezone=UTC 
    username: root
    password: a6643699
    driver-class-name: com.mysql.cj.jdbc.Driver
    
#設定 Eureka 註冊的路徑    
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:28990/eureka/